---
- name: Create log folders
  file:
    path: "{{ vhost_base_path }}/{{ item['host'] }}/logs"
    state: directory
    owner: "{{ item['user'] }}"
    group: "{{ item['group'] }}"
  with_items: vhost_sites

- name: Create logs symlinks
  file:
    src: "{{ vhost_base_path }}/{{ item['host'] }}/logs"
    dest: /home/{{ item['user'] }}/logs
    state: link
    owner: "{{ item['user'] }}"
    group: "{{ item['group'] }}"
  with_items: vhost_sites

- name: Create apache2 vhosts
  template:
    src: apache2/vhost.conf.j2
    dest: /etc/apache2/sites-available/{{ item['host'] }}.conf
  with_items: vhost_sites

- name: Enable apache2 vhosts
  file:
    src: /etc/apache2/sites-available/{{ item['host'] }}.conf
    dest: /etc/apache2/sites-enabled/{{ item['host'] }}.conf
    state: link
  with_items: vhost_sites
  notify: Restart apache
  when: "item['disabled']|default(false) != True"
